//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspnetStudentAssignmentSubmission
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string CourseType { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> TopicId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<System.DateTime> AssignmentDueDate { get; set; }
        public Nullable<System.DateTime> AssignmentSubmittedDate { get; set; }
        public string AssignmentFileName { get; set; }
        public string TeacherComments { get; set; }
    
        public virtual AspNetClass AspNetClass { get; set; }
        public virtual AspnetLesson AspnetLesson { get; set; }
        public virtual AspNetStudent AspNetStudent { get; set; }
        public virtual AspnetSubjectTopic AspnetSubjectTopic { get; set; }
    }
}
