//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetTimeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetTimeTable()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> SlotID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Day { get; set; }
        public Nullable<bool> IsPopulated { get; set; }
        public string Teacher_ID { get; set; }
        public Nullable<int> SessionID { get; set; }
    
        public virtual AspNetRoom AspNetRoom { get; set; }
        public virtual AspNetSession AspNetSession { get; set; }
        public virtual AspNetSubject AspNetSubject { get; set; }
        public virtual AspNetTimeslot AspNetTimeslot { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
