//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspnetStudentAssignment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual AspnetLesson AspnetLesson { get; set; }
    }
}
