//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson_Session
    {
        public int Id { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual AspnetLesson AspnetLesson { get; set; }
        public virtual AspNetSession AspNetSession { get; set; }
    }
}
